// NOTE: The provided GitHub token is not a valid URL for a word list.
// Instead, we've implemented separate lists for solutions and valid guesses.

// List of words that can be used as solutions - common, well-known 5-letter words
const SOLUTION_WORDS = [
    'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN',
    'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE',
    'ALONG', 'ALTER', 'AMONG', 'ANGER', 'ANGLE', 'ANGRY', 'ANKLE', 'APART', 'APPLE', 'APPLY',
    'ARENA', 'ARGUE', 'ARISE', 'ARMED', 'ARMOR', 'ARMY', 'ARRAY', 'ARROW', 'ASSET', 'ASSIST',
    'AVOID', 'AWARD', 'AWARE', 'AWFUL', 'BADLY', 'BASIC', 'BASIS', 'BEACH', 'BEARD', 'BEAST',
    'BEGIN', 'BEING', 'BELOW', 'BENCH', 'BERRY', 'BIRTH', 'BLACK', 'BLADE', 'BLAME', 'BLANK',
    'BLAST', 'BLEED', 'BLEND', 'BLESS', 'BLIND', 'BLOCK', 'BLOOD', 'BLOOM', 'BLUES', 'BLUFF',
    'BOARD', 'BOAST', 'BONUS', 'BOOST', 'BOOTH', 'BOUND', 'BRACE', 'BRAIN', 'BRAKE', 'BRAND',
    'BRAVE', 'BREAD', 'BREAK', 'BREED', 'BRICK', 'BRIEF', 'BRING', 'BRISK', 'BROAD', 'BROKE',
    'BROWN', 'BRUSH', 'BUILD', 'BUILT', 'BUYER', 'CABLE', 'CACHE', 'CANDY', 'CANON', 'CARDS',
    'CARRY', 'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHALK', 'CHARM', 'CHART', 'CHASE', 'CHEAP',
    'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHILL', 'CHINA', 'CHORD', 'CIVIL', 'CLAIM', 'CLASS',
    'CLEAN', 'CLEAR', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB', 'CLOCK', 'CLOSE', 'CLOTH', 'CLOUD',
    'CLOWN', 'COACH', 'COAST', 'COLOR', 'COMIC', 'COUNT', 'COURT', 'COVER', 'CRAFT', 'CRASH',
    'CREAM', 'CRIME', 'CRISP', 'CROSS', 'CROWD', 'CROWN', 'CRUSH', 'CURVE', 'CYCLE', 'DAILY',
    'DANCE', 'DATUM', 'DEATH', 'DEBUT', 'DELAY', 'DEPTH', 'DEVIL', 'DIARY', 'DIRTY', 'DISCO',
    'DIVER', 'DOUBT', 'DRAFT', 'DRAIN', 'DRAWN', 'DREAM', 'DRESS', 'DRILL', 'DRINK', 'DRIVE',
    'EARLY', 'EARTH', 'ELITE', 'EMPTY', 'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'ERROR',
    'EVENT', 'EXACT', 'EXIST', 'EXTRA', 'FAINT', 'FAITH', 'FALSE', 'FAULT', 'FAVOR', 'FEAST',
    'FEWER', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY', 'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLASH',
    'FLEET', 'FLESH', 'FLOAT', 'FLOOD', 'FLOOR', 'FLUID', 'FOCUS', 'FORCE', 'FORTH', 'FORTY',
    'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FROST', 'FRUIT', 'FULLY',
    'FUNNY', 'GHOST', 'GIANT', 'GLASS', 'GLOBE', 'GLORY', 'GOING', 'GRACE', 'GRADE', 'GRAIN',
    'GRAND', 'GRANT', 'GRASS', 'GREAT', 'GREEN', 'GRIEF', 'GROSS', 'GROUP', 'GUARD', 'GUESS',
    'GUEST', 'GUIDE', 'GUILT', 'HABIT', 'HAIRY', 'HAPPY', 'HARSH', 'HASTE', 'HASTY', 'HEART',
    'HEAVY', 'HELLO', 'HENCE', 'HENRY', 'HORSE', 'HOTEL', 'HOUSE', 'HUMAN', 'HURRY', 'IDEAL',
    'IMAGE', 'IMPLY', 'INDEX', 'INNER', 'INPUT', 'IRONY', 'ISSUE', 'ITEM', 'JAPAN', 'JIMMY',
    'JOINT', 'JONES', 'JUDGE', 'KNIFE', 'KNOCK', 'KNOWN', 'LABEL', 'LABOR', 'LARGE', 'LASER',
    'LATER', 'LAUGH', 'LAYER', 'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEMON', 'LEVEL',
    'LIGHT', 'LIMIT', 'LINKS', 'LIVER', 'LIVES', 'LOCAL', 'LOGIC', 'LOOSE', 'LORRY', 'LOWER',
    'LUCKY', 'LUNCH', 'LYING', 'MAGIC', 'MAJOR', 'MAKER', 'MARCH', 'MARIA', 'MATCH', 'MAYBE',
    'MAYOR', 'MEANT', 'MEDIA', 'METAL', 'METER', 'MIGHT', 'MINOR', 'MINUS', 'MIXED', 'MODEL',
    'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVIE', 'MUSIC', 'NAIVE',
    'NASTY', 'NAVAL', 'NERVE', 'NEVER', 'NEWLY', 'NEXUS', 'NIGHT', 'NINTH', 'NOBLE', 'NOISE',
    'NORTH', 'NOTCH', 'NOTED', 'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER',
    'OTHER', 'OUGHT', 'OUTER', 'OWING', 'OWNER', 'OXIDE', 'PANEL', 'PANIC', 'PAPER', 'PARTY',
    'PASTE', 'PATCH', 'PAUSE', 'PEACE', 'PETER', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PIECE',
    'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'POINT', 'POKER', 'POLAR',
    'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRIZE', 'PROOF',
    'PROUD', 'PROVE', 'PROXY', 'PULSE', 'PUNCH', 'PUPIL', 'PURSE', 'QUEEN', 'QUERY', 'QUEST',
    'QUICK', 'QUIET', 'QUITE', 'QUOTE', 'RADIO', 'RAISE', 'RANGE', 'RAPID', 'RATIO', 'REACH',
    'READY', 'REFER', 'RELAX', 'REPLY', 'RIGHT', 'RIGID', 'RIVAL', 'RIVER', 'ROAST', 'ROBIN',
    'ROBOT', 'ROGER', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RUGBY', 'RULER', 'RULED',
    'RURAL', 'RUSTY', 'SADLY', 'SAINT', 'SALAD', 'SALLY', 'SALON', 'SANDY', 'SATIN', 'SAUCE',
    'SCALE', 'SCARY', 'SCENE', 'SCENT', 'SCORE', 'SCREW', 'SEIZE', 'SENSE', 'SERVE', 'SEVEN',
    'SHADE', 'SHAFT', 'SHAKE', 'SHALL', 'SHAME', 'SHAPE', 'SHARE', 'SHARP', 'SHEEP', 'SHEER',
    'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHINE', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORE', 'SHORT',
    'SHOWN', 'SIGHT', 'SILLY', 'SINCE', 'SIXTH', 'SIXTY', 'SKIRT', 'SLEEP', 'SLICE', 'SLIDE',
    'SLOPE', 'SMALL', 'SMART', 'SMILE', 'SMITH', 'SMOKE', 'SNAKE', 'SOBER', 'SOLAR', 'SOLID',
    'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPARK', 'SPEAK', 'SPEED', 'SPELL',
    'SPEND', 'SPENT', 'SPITE', 'SPLIT', 'SPOKE', 'SPORT', 'SPRAY', 'STAFF', 'STAGE', 'STAKE',
    'STAMP', 'STAND', 'START', 'STATE', 'STEAM', 'STEEL', 'STEEP', 'STICK', 'STILL', 'STOCK',
    'STONE', 'STORE', 'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR',
    'SUITE', 'SUPER', 'SWEET', 'SWING', 'SWISS', 'SWORD', 'TABLE', 'TAKEN', 'TALLY', 'TASTE',
    'TAXES', 'TEACH', 'TEETH', 'TEMPT', 'TENSE', 'THANK', 'THEFT', 'THEME', 'THERE', 'THICK',
    'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THROW', 'TIGHT', 'TIMER',
    'TIRED', 'TITLE', 'TODAY', 'TOKEN', 'TOOTH', 'TOPIC', 'TORCH', 'TOTAL', 'TOUCH', 'TOUGH',
    'TOWEL', 'TOWER', 'TOXIC', 'TRACE', 'TRACK', 'TRADE', 'TRAIL', 'TRAIN', 'TREAT', 'TREND',
    'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TRUCK', 'TRULY', 'TRUNK', 'TRUST', 'TRUTH',
    'TWICE', 'TWIST', 'ULTRA', 'UNCLE', 'UNDER', 'UNION', 'UNITE', 'UNITY', 'UNTIL', 'UPPER',
    'UPSET', 'URBAN', 'USAGE', 'USUAL', 'UTTER', 'VAGUE', 'VALID', 'VALUE', 'VAPOR', 'VAULT',
    'VENUE', 'VERSE', 'VIDEO', 'VIRUS', 'VISIT', 'VITAL', 'VIVID', 'VOCAL', 'VOICE', 'WASTE',
    'WATCH', 'WATER', 'WEIGH', 'WEIRD', 'WHALE', 'WHEAT', 'WHEEL', 'WHERE', 'WHICH', 'WHILE',
    'WHITE', 'WHOLE', 'WHOSE', 'WIDOW', 'WIDTH', 'WINDY', 'WOMAN', 'WORLD', 'WORRY', 'WORSE',
    'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRITE', 'WRONG', 'WROTE', 'YACHT', 'YIELD', 'YOUNG', 
    'YOUTH', 'ZEROS', 'ZONE', 'ZOOM'
];

// Additional 5-letter words that are valid guesses but not used as solutions
const ADDITIONAL_VALID_WORDS = [
    'ABACK', 'ABASE', 'ABATE', 'ABBEY', 'ABBOT', 'ABHOR', 'ABIDE', 'ABODE', 'ABORT', 'ABYSS',
    'ACORN', 'ACRID', 'ACTOR', 'ADAGE', 'ADAPT', 'ADEPT', 'ADMIN', 'AFFIX', 'AFOOT', 'AGILE',
    'AGING', 'AGONY', 'AGREE', 'AISLE', 'ALAMO', 'ALBUM', 'ALERT', 'ALGAE', 'ALIBI', 'ALIEN',
    'ALIGN', 'ALIKE', 'ALLEY', 'ALLOT', 'ALLOY', 'ALOFT', 'ALOHA', 'ALPHA', 'ALTAR', 'ALTER',
    'AMASS', 'AMAZE', 'AMBER', 'AMBLE', 'AMEND', 'AMISS', 'AMITY', 'AMUSE', 'ANGEL', 'ANGER',
    'ANGLE', 'ANGRY', 'ANGST', 'ANIME', 'ANKLE', 'ANNEX', 'ANNOY', 'ANODE', 'ANTIC', 'ANVIL',
    'AORTA', 'APHID', 'APING', 'APNEA', 'APPLE', 'APPLY', 'APRON', 'APTLY', 'ARBOR', 'ARDOR',
    'AREAS', 'ARENA', 'ARGON', 'ARGOT', 'ARGUE', 'ARISE', 'ARMOR', 'AROMA', 'AROSE', 'ARRAY',
    'ARROW', 'ARSON', 'ARTSY', 'ASCOT', 'ASHEN', 'ASIDE', 'ASKEW', 'ASSAY', 'ASSES', 'ASSET',
    'ASTER', 'ATOMS', 'ATONE', 'ATTIC', 'AUDIO', 'AUDIT', 'AUGUR', 'AUNTY', 'AVAIL', 'AVERT',
    'AVIAN', 'AVOID', 'AWAIT', 'AWAKE', 'AWARD', 'AWARE', 'AWFUL', 'AWOKE', 'AXIAL', 'AXIOM',
    'AXION', 'AZURE', 'BACON', 'BADGE', 'BADLY', 'BAGEL', 'BAGGY', 'BAKED', 'BAKER', 'BALMY',
    'BANAL', 'BANJO', 'BARGE', 'BARON', 'BASAL', 'BASIC', 'BASIL', 'BASIN', 'BASIS', 'BASTE',
    'BATCH', 'BATHE', 'BATON', 'BATTY', 'BAWDY', 'BAYOU', 'BEACH', 'BEADY', 'BEARD', 'BEAST',
    'BEATS', 'BEECH', 'BEEFY', 'BEFIT', 'BEGAN', 'BEGAT', 'BEGET', 'BEGIN', 'BEGUN', 'BEING',
    'BELCH', 'BELIE', 'BELLE', 'BELLY', 'BELOW', 'BENCH', 'BERET', 'BERRY', 'BERTH', 'BESET',
    'BETEL', 'BEVEL', 'BEZEL', 'BIBLE', 'BICEP', 'BIDDY', 'BIGOT', 'BILGE', 'BILLY', 'BINGE',
    'BINGO', 'BIOME', 'BIRCH', 'BIRTH', 'BISON', 'BITTY', 'BLACK', 'BLADE', 'BLAME', 'BLAND',
    'BLANK', 'BLARE', 'BLAST', 'BLAZE', 'BLEAK', 'BLEAT', 'BLEED', 'BLEEP', 'BLEND', 'BLESS',
    'BLIMP', 'BLIND', 'BLINK', 'BLISS', 'BLITZ', 'BLOAT', 'BLOCK', 'BLOKE', 'BLOND', 'BLOOD',
    'BLOOM', 'BLOWN', 'BLUER', 'BLUFF', 'BLUNT', 'BLURB', 'BLURT', 'BLUSH', 'BOARD', 'BOAST',
    'BOBBY', 'BONEY', 'BONGO', 'BONUS', 'BOOBY', 'BOOST', 'BOOTH', 'BOOTY', 'BOOZE', 'BORAX',
    'BORED', 'BORER', 'BORNE', 'BOSOM', 'BOSSY', 'BOTCH', 'BOUGH', 'BOULE', 'BOUND', 'BOWEL'
];

// Combine both lists for valid guesses
const ALL_VALID_WORDS = [...SOLUTION_WORDS, ...ADDITIONAL_VALID_WORDS];

// Get a random word from the solution list
function getRandomWord() {
    return SOLUTION_WORDS[Math.floor(Math.random() * SOLUTION_WORDS.length)];
}

// Check if a word is in either list of valid words
function isValidWord(word) {
    return ALL_VALID_WORDS.includes(word.toUpperCase());
} 